name: pratokente
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

module:
    androidX: true 
    
environment:
  sdk: ">=2.12.0 <3.0.0"
  # flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^1.0.2
  firebase_storage: ^8.0.1
  cloud_firestore: ^1.0.3
  cloud_functions: ^1.0.2

  # Firebase Authentications
  firebase_auth: ^1.0.1
  google_sign_in: ^5.0.1
  sign_in_with_apple: ^3.0.0
  # flutter_facebook_auth: ^3.1.1

  intl: ^0.17.0
  #qr_flutter: ^4.0.0
  qr_code_scanner: ^0.4.0
  path_provider: ^2.0.1

  # Stacked State Management
  stacked: ^2.1.0
  stacked_services: ^0.8.3
  stacked_firebase_auth: ^0.2.1
  flutter_credit_card: ^2.0.0

  # storage
  shared_preferences: ^2.0.5

  get_it: ^6.1.1
  image_picker: ^0.7.4
  cached_network_image: ^3.0.0
  observable_ish: ^3.0.0
  animations: ^2.0.0
  material_floating_search_bar: ^0.3.3
  uuid: ^3.0.3
  flutter_hooks: ^0.16.0
  # auto_route: ^0.6.9 # using stacked generator instead
  http: ^0.13.1
  #webview_flutter: ^2.0.3
  js: ^0.6.3
  rxdart: ^0.26.0
  flutter_typeahead: ^3.1.1
  scroll_to_index: ^2.0.0
  universal_html: ^2.0.8
  percent_indicator: ^3.0.1
  logger: ^1.0.0
  flutter_signin_button: ^2.0.0
  shimmer_animation: ^2.0.0

  persistent_bottom_nav_bar: ^4.0.2
  freezed_annotation: ^0.14.1
  json_annotation: ^4.0.1
  delayed_display: ^2.0.0
  url_strategy: ^0.2.0
  places_service: ^0.1.0+2

    #Date and Time 
  date_time_picker: ^2.0.0

    #verify network 
  connectivity: ^3.0.4
  flutter_fadein: ^2.0.0
  auth_buttons: ^1.0.1+3
  carousel_slider: ^4.0.0-nullsafety.0
  money2: ^2.2.1
  #Pagination Controller
  paginate_firestore:
  
  #Pratokente UI Package
  pratokente_ui:
    path: ../pratokente_ui/
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  flutter_stripe: ^1.0.2
  pay: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  # auto_route_generator:
  stacked_generator: ^0.4.1
  freezed: ^0.14.1+3
  json_serializable: 4.1.1
  flutter_dotenv: ^4.0.0-nullsafety.1

  # Testing
  mockito:

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo/pratokente.png"

  
  #data Models
  freezed: ^0.14.1+2
  json_serializable: ^4.1.0
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  uses-material-design: true
  assets:
    - .env
    - assets/Template1/image/SplashScreenTemplate1.png
    - assets/Template1/image/icon.png
    - assets/Template1/image/onBoarding1.jpeg
    - assets/Template1/image/onBoarding2.jpeg
    - assets/Template1/image/onBoarding3.jpeg
    - assets/Template1/image/chosseBackground.jpeg
    - assets/Template1/image/loginBackground.jpeg
    - assets/Template1/image/marker.png
    - assets/Template1/image/profileBackground.png
    - assets/Template1/image/backgroundProfile.png
    - assets/Template1/image/backgroundLine.png
    - assets/Template1/banner/1.jpg
    - assets/Template1/banner/2.jpg
    - assets/Template1/banner/3.jpg
    - assets/Template1/banner/4.jpg
    - assets/Template1/banner/5.jpg
    - assets/Template1/banner/6.jpg
    - assets/Template1/banner/7.jpg
    - assets/Template1/map_style.txt
    - assets/icon/profile.png
    - assets/icon/box.png
    - assets/icon/trash_icon.svg
    - assets/icon/cart_icon.svg
    - assets/icon/notification.png
    - assets/icon/notificationIlustration.png
    - assets/icon/callCenterIlustration.png
    - assets/icon/discount.png
    - assets/icon/card.png
    - assets/icon/callCenter.png
    - assets/icon/setting.png
    - assets/icon/style.png
    - assets/icon/breakfast.png
    - assets/icon/caffe.png
    - assets/icon/dinner.png
    - assets/icon/healty.png
    - assets/icon/Lunch.png
    - assets/icon/fashfood.png
    - assets/Template2/choseLoginBackground.png
    - assets/Template2/loginBackground.png
    - assets/Template2/onBoarding1.png
    - assets/Template2/onBoarding2.png
    - assets/Template2/onBoarding3.png
    - assets/Template2/splashBackground.png
    - assets/Template2/logo.png
    - assets/Template2/facebook.png
    - assets/Template2/google.png
    - assets/Template2/setting.png
    - assets/Template2/girlcallcenter.png
    - assets/image/plate_food/1.png
    - assets/image/plate_food/2.png
    - assets/image/plate_food/3.png
    - assets/image/plate_food/4.png
    - assets/image/plate_food/5.png
    - assets/image/plate_food/6.png
    - assets/image/plate_food/7.png
    - assets/image/plate_food/8.png
    - assets/image/plate_food/9.png
    - assets/image/plate_food/10.png
    - assets/image/plate_food/11.png
    - assets/image/plate_food/12.png
    - assets/image/plate_food/13.png
    - assets/image/plate_food/14.png
    - assets/image/plate_food/15.png
    - assets/image/plate_food/16.png
    - assets/image/plate_food/17.png
    - assets/image/plate_food/18.png
    - assets/image/plate_food/19.png
    - assets/image/plate_food/20.png
    - assets/image/image_recipe/recipe1.jpg
    - assets/image/image_recipe/recipe2.jpg
    - assets/image/image_recipe/recipe3.jpg
    - assets/image/image_recipe/recipe4.jpg
    - assets/image/image_recipe/recipe5.png
    - assets/image/image_recipe/recipe6.png
    - assets/image/image_recipe/recipe7.png
    - assets/image/image_recipe/recipe8.png
    - assets/image/image_recipe/recipe9.jpg
    - assets/image/image_recipe/recipe10.jpg
    - assets/image/image_recipe/recipe11.jpg
    - assets/image/image_recipe/recipe12.jpg
    - assets/image/image_recipe/recipe13.jpg
    - assets/image/image_recipe/recipe14.jpg
    - assets/image/image_recipe/recipe15.jpg
    - assets/image/image_recipe/recipe16.jpg
    - assets/image/image_recipe/recipe17.jpg
    - assets/image/image_recipe/recipe18.jpg
    - assets/image/image_recipe/recipe19.jpg
    - assets/image/image_recipe/recipe20.jpg
    - assets/image/image_recipe/recipe21.jpg
    - assets/image/image_recipe/recipe22.jpg
    - assets/image/image_recipe/recipe23.jpg
    - assets/image/image_recipe/recipe24.jpg
    - assets/image/image_recipe/recipe25.jpg
    - assets/image/image_recipe/recipe26.jpg
    - assets/image/image_recipe/recipe27.jpg
    - assets/image/image_recipe/recipe28.jpg
    - assets/image/image_recipe/recipe29.jpg
    - assets/image/image_recipe/recipe30.jpg
    - assets/image/image_recipe/recipe31.jpg
    - assets/image/image_recipe/recipe32.jpg
    - assets/image/image_recipe/recipe33.jpg
    - assets/image/image_recipe/recipe34.jpg
    - assets/image/image_recipe/recipe35.jpg
    - assets/image/image_recipe/recipe36.jpg
    - assets/image/image_recipe/detailRecipe.png
    - assets/Template2/icon/iconAmerican.png
    - assets/Template2/icon/iconBreakfast.png
    - assets/Template2/icon/iconBurgers.png
    - assets/Template2/icon/iconPizza.png
    - assets/Template2/icon/bookmark.png
    - assets/Template2/icon/photos.png
    - assets/Template2/icon/ratting.png
    - assets/Template2/icon/searchEmpty.png
    - assets/Template2/icon/logout.png
    - assets/Template2/icon/aboutApps.png
    - assets/Template2/loginBackground.png
    - assets/Template2/logo.png
    - assets/Template2/icon/callCenter.png
    - assets/Template2/icon/editProfile.png
    - assets/icon/share.png
    - assets/icon/rattingPlus.png
    - assets/icon/report.png
    - assets/icon/bookmark.png
    - assets/icon/wifi.png
    - assets/Template2/ilustrasion/emptyCart.png
    - assets/Template2/profile.png
    - assets/Template2/backgroundProfile.png
    - assets/Template2/creditCard.png
    - assets/Template2/cod.png
    - assets/Template2/paypal.png
    - assets/Template2/visa.png
    - assets/Template2/money.png
    - assets/Template2/house.png
    - assets/Template2/personal.png
    - assets/Template2/checklist.png
    - assets/Template2/category/category1.jpg
    - assets/Template2/category/category2.jpg
    - assets/Template2/category/category3.jpg
    - assets/Template2/category/category4.jpg
    - assets/Template2/category/category5.jpg
    - assets/Template2/category/category6.jpg
    - assets/Template2/category/category7.jpg
    - assets/Template2/category/category8.jpg
    - assets/Template2/category/category9.jpg
    - assets/Template2/category/category10.jpg
    - assets/app_images/splashBackground.png
    - assets/app_images/logo.png
    - assets/carousel/photo1.png
    - assets/carousel/photo2.jpeg
    - assets/carousel/photo3.jpeg
    - assets/logo/pratokente.png